export const LOAD_IMAGES_PENDING = "LOAD_IMAGES_PENDING";
export const LOAD_IMAGES_SUCCESS = "LOAD_IMAGES_SUCCESS";
export const LOAD_IMAGES_FAIL = "LOAD_IMAGES_FAIL";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const UPDATE_TAG = "UPDATE_TAG";
